### ISSUE TITLE
find out what the deal with the '^M' in the output GED files is

### ISSUE THREAD

**Issue by poozipotti** [poozipotti/CS555_GEDCOM#1]
looking at a parsed GED there are '^M' at the end of all the lines and it is super annoying and i have no idea why it does that.

**Comment by jr6321** [comment]
The problem is that Unix ends lines with \n while Windows ends lines with \r\n.  Your GED file was probably created on a Windows machine.   The dos2unix command is one solution.  You can also use sed, tr, and a variety of other approaches to remove the ^M
